2015-12-02 16:52:45,895 [5] ERROR AccessControl.Web.Services.ApplicationSignInManager - An error occurred while authentication
MassTransit.RequestFaultException: The AccessControl.Contracts.Commands.Security.IAuthenticateUser request faulted: При установлении соединения с SQL Server произошла ошибка, связанная с сетью или с определенным экземпляром. Сервер не найден или недоступен. Убедитесь, что имя экземпляра указано правильно и что на SQL Server разрешены удаленные соединения. (provider: SQL Network Interfaces, error: 26 - Ошибка при обнаружении указанного сервера или экземпляра)
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MassTransit.MessageRequestClient`2.<MassTransit-IRequestClient<TRequest\,TResponse>-Request>d__4.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в AccessControl.Web.Services.ApplicationSignInManager.<PasswordSignInAsync>d__5.MoveNext() в D:\Work\Crossover\AccessControlSystem\src\AccessControl.Web\Services\ApplicationSignInManager.cs:строка 51
2015-12-03 00:11:31,327 [7] ERROR AccessControl.Web.Services.ApplicationSignInManager - An error occurred while authentication
MassTransit.RequestFaultException: The AccessControl.Contracts.Commands.Security.IAuthenticateUser request faulted: При установлении соединения с SQL Server произошла ошибка, связанная с сетью или с определенным экземпляром. Сервер не найден или недоступен. Убедитесь, что имя экземпляра указано правильно и что на SQL Server разрешены удаленные соединения. (provider: SQL Network Interfaces, error: 26 - Ошибка при обнаружении указанного сервера или экземпляра)
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MassTransit.MessageRequestClient`2.<MassTransit-IRequestClient<TRequest\,TResponse>-Request>d__4.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в AccessControl.Web.Services.ApplicationSignInManager.<PasswordSignInAsync>d__5.MoveNext() в D:\Work\Crossover\AccessControlSystem\src\AccessControl.Web\Services\ApplicationSignInManager.cs:строка 51
2015-12-04 12:27:02,424 [11] ERROR AccessControl.Web.Services.ApplicationSignInManager - An error occurred while authentication
MassTransit.RequestTimeoutException: Timeout waiting for response, RequestId: 885e0000-5ad1-2cd0-2209-08d2fc8cf2cc
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MassTransit.MessageRequestClient`2.<MassTransit-IRequestClient<TRequest\,TResponse>-Request>d__4.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в AccessControl.Web.Services.ApplicationSignInManager.<PasswordSignInAsync>d__5.MoveNext() в D:\Work\Crossover\AccessControlSystem\src\AccessControl.Web\Services\ApplicationSignInManager.cs:строка 51
2015-12-05 02:33:12,628 [9] ERROR AccessControl.Web.Services.ApplicationSignInManager - An error occurred while authentication
MassTransit.RabbitMqTransport.RabbitMqConnectionException: Connect failed: evgeny@192.168.1.220:5672/ ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 192.168.1.220:5672
   в System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   в System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   в RabbitMQ.Client.Impl.SocketFrameHandler.Connect(TcpClient socket, AmqpTcpEndpoint endpoint, Int32 timeout)
   --- Конец трассировки внутреннего стека исключений ---
   в RabbitMQ.Client.Impl.SocketFrameHandler.Connect(TcpClient socket, AmqpTcpEndpoint endpoint, Int32 timeout)
   в RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, Int32 timeout)
   в RabbitMQ.Client.Framing.Impl.ProtocolBase.CreateFrameHandler(AmqpTcpEndpoint endpoint, Func`2 socketFactory, Int32 timeout)
   в RabbitMQ.Client.ConnectionFactory.CreateFrameHandler()
   в RabbitMQ.Client.ConnectionFactory.CreateConnection()
   --- Конец трассировки внутреннего стека исключений ---
   в RabbitMQ.Client.ConnectionFactory.CreateConnection()
   в MassTransit.RabbitMqTransport.Integration.RabbitMqConnectionCache.<SendUsingNewConnection>d__13.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MassTransit.RabbitMqTransport.Integration.RabbitMqConnectionCache.ConnectionScope.<Attach>d__5.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MassTransit.RabbitMqTransport.Integration.RabbitMqConnectionCache.<SendUsingExistingConnection>d__14.MoveNext()
   --- Конец трассировки внутреннего стека исключений ---
   в MassTransit.RabbitMqTransport.Integration.RabbitMqConnectionCache.<SendUsingExistingConnection>d__14.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MassTransit.RabbitMqTransport.Integration.RabbitMqModelCache.<SendUsingNewModel>d__6.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MassTransit.RabbitMqTransport.RabbitMqSendTransport.<MassTransit-Transports-ISendTransport-Send>d__6`1.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MassTransit.MessageRequestClient`2.<MassTransit-IRequestClient<TRequest\,TResponse>-Request>d__4.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в AccessControl.Web.Services.ApplicationSignInManager.<PasswordSignInAsync>d__5.MoveNext() в D:\Work\Crossover\AccessControlSystem\src\AccessControl.Web\Services\ApplicationSignInManager.cs:строка 48
2015-12-05 04:10:58,307 [11] ERROR AccessControl.Web.Services.ApplicationSignInManager - An error occurred while authentication
MassTransit.RequestTimeoutException: Timeout waiting for response, RequestId: 885e0000-5ad1-2cd0-609f-08d2fd10d98f
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MassTransit.MessageRequestClient`2.<MassTransit-IRequestClient<TRequest\,TResponse>-Request>d__4.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в AccessControl.Web.Services.ApplicationSignInManager.<PasswordSignInAsync>d__5.MoveNext() в D:\Work\Crossover\AccessControlSystem\src\AccessControl.Web\Services\ApplicationSignInManager.cs:строка 48
2015-12-05 05:25:18,145 [6] ERROR AccessControl.Web.Services.LdapUserStore - An error occurred while searching a user
MassTransit.RequestFaultException: The AccessControl.Contracts.Commands.Search.IFindUserByName request faulted: Ссылка на объект не указывает на экземпляр объекта.
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в MassTransit.MessageRequestClient`2.<MassTransit-IRequestClient<TRequest\,TResponse>-Request>d__4.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в AccessControl.Web.Services.LdapUserStore.<FindByNameAsync>d__8.MoveNext() в D:\Work\Crossover\AccessControlSystem\src\AccessControl.Web\Services\LDAPUserStore.cs:строка 53
